### ISSUE TITLE
Current ToDo's

### ISSUE THREAD

**Issue by platocrat** [orangewit3/supply_chain_simulator#12]
# ToDo's 
## Back-end:
- [ ] Add more events 
- [ ] Clean-up code (?)

## Front-end:
- [ ] State management for Solidity events: 
  - [ ] For CocoaBeanFarmer and Manufacturer contracts
- [ ] Visualizations of event data
- [x] Switch to using [ethers.js](https://github.com/ethers-io/ethers.js) instead of web3.js because it's much easier to use (in general, and) for production.
- [x] Switch to using Goerli testnet (because it's better for production testing)
- [x] Add Blocknative's [Notify.js](https://docs.blocknative.com/notify) and [Onboard.js](https://docs.blocknative.com/onboard)
- Manually implement digital wallet integration
